import {
Copy,
Download,
Brain,
Layers,
MessageCircle,
FileText
} from "lucide-react";


export default function Summary(){


return (

<div className="summary-page">



<div className="summary-header">


<div>

<h1>
Networking Fundamentals - Chapter 4
</h1>


<p>
PDF • 32 pages • Generated by StudyMind AI
</p>


</div>


<div className="summary-buttons">


<button>
<Copy size={18}/>
Copy
</button>


<button>
<Download size={18}/>
Export
</button>


</div>


</div>





<div className="summary-grid">





{/* SUMMARY */}


<div className="summary-card">


<div className="ai-label">
✨ AI Summary
</div>



<h2>
Key Takeaways
</h2>



<ul>

<li>
VLANs divide a physical network into logical networks.
</li>


<li>
Trunk links carry multiple VLANs using 802.1Q.
</li>


<li>
OSPF uses link-state advertisements to calculate routes.
</li>


<li>
ACLs control traffic based on rules.
</li>


<li>
NAT allows private devices to access the internet.
</li>


</ul>





<h2>
Chapter Structure
</h2>



<div className="chapter">

<span>
4.1 VLAN Fundamentals
</span>

<span>
Pages 1-8
</span>


</div>



<div className="chapter">

<span>
4.2 Trunking
</span>

<span>
Pages 9-14
</span>


</div>



<div className="chapter">

<span>
4.3 Routing Protocols
</span>

<span>
Pages 15-24
</span>


</div>



</div>








{/* ACTIONS */}



<div className="summary-side">



<div className="side-card">


<h3>
Turn this document into
</h3>



<button>

<Brain/>

Generate Quiz

</button>



<button>

<Layers/>

Create Flashcards

</button>



<button>

<MessageCircle/>

Discuss with AI Tutor

</button>



</div>






<div className="side-card">


<h3>
Document Info
</h3>


<div className="info-row">

<span>
Type
</span>

<strong>
PDF
</strong>

</div>


<div className="info-row">

<span>
Pages
</span>

<strong>
32
</strong>

</div>


<div className="info-row">

<span>
Size
</span>

<strong>
4.1 MB
</strong>

</div>


</div>



</div>



</div>


</div>


)

}